version: "3.6"

services:
  ghp-pr-sync:
    image: ghp-pr-sync
    container_name: ghp-pr-sync
    environment:
      - "TZ=America/Vancouver"
      - "SYNC_CRON=0 */3 * * *"
      - "GITHUB_TOKEN="
      - "GITHUB_ORG=hashicorp"
      - "GITHUB_REPO=terraform-provider-azurerm"
      - "GITHUB_PROJECT_NUMBER="
      - "GITHUB_AUTHORS="
